PICTS = FTL.pict2e FTL2.pict2e bandl2.pict2e bandl3.pict2e bandlimit.pict2e eganallp.pict2e egdiglp.pict2e linphaseI.pict2e linphaseII.pict2e linphaseIII.pict2e linphaseIV.pict2e s-zplane.pict2e

%.pict2e: %.fig
	fig2dev $*.fig $*.pict2e

all: $(PICTS)

