PICTS = circle.pict2e convequiva.pict2e convequivb.pict2e convequivc.pict2e convequivd.pict2e convequive.pict2e convequivf.pict2e dft2a.pict2e dft2b.pict2e dft2c.pict2e dft2d.pict2e dfta.pict2e dftb.pict2e dftc.pict2e dftd.pict2e finitea.pict2e finiteb.pict2e finitec.pict2e finited.pict2e fir.pict2e ils.pict2e lconva.pict2e lconvb.pict2e lconvc.pict2e lconvd.pict2e lconve.pict2e nconva.pict2e nconvb.pict2e nconvc.pict2e overadda.pict2e overaddb.pict2e overaddc.pict2e overaddd.pict2e oversavea.pict2e oversaveb.pict2e system.pict2e

%.pict2e: %.fig
	fig2dev $*.fig $*.pict2e

all: $(PICTS)

