PICTS = active.pict2e adder.pict2e altreal.pict2e chebyresp.pict2e \
		circn2.pict2e circn6.pict2e delayfilt.pict2e delayfreq.pict2e desproc.pict2e \
		different.pict2e doublelow.pict2e ellipse.pict2e filtdes.pict2e \
		gensim.pict2e gensim2.pict2e integ.pict2e ldiv1.pict2e ldiv2.pict2e \
		low2bp.pict2e low2bs.pict2e low2hi.pict2e lpfig.pict2e lpfilt.pict2e \
		multip.pict2e parallel.pict2e real3.pict2e realh.pict2e realh1.pict2e \
		realh2.pict2e realizeh.pict2e rlc.pict2e sfop.pict2e sfoz.pict2e \
		sop.pict2e splane.pict2e ssoz.pict2e

%.pict2e: %.fig
	fig2dev $*.fig $*.pict2e

all: $(PICTS)

