PICTS = adc.pict2e convtrain.pict2e daconv.pict2e daconvinput.pict2e \
		daconvoutput.pict2e daimpulse.pict2e downsampler.pict2e dsp.pict2e \
		expander.pict2e fixedpoint.pict2e fohapprox.pict2e freqdown.pict2e \
		freqdowna.pict2e freqdownalias.pict2e freqdownaliasa.pict2e \
		freqdownaliasb.pict2e freqdownaliasc.pict2e freqdownaliasd.pict2e \
		freqdownaliase.pict2e freqdownaliasf.pict2e freqdownb.pict2e freqdownc.pict2e \
		freqdownd.pict2e freqdowne.pict2e gendown.pict2e interdec.pict2e \
		lininterp.pict2e lpfilt.pict2e prdexten.pict2e quant.pict2e \
		recon.pict2e rectpulse.pict2e sampling.pict2e spectrum.pict2e tsec.pict2e \
		zoh.pict2e zohapprox.pict2e

%.pict2e: %.fig
	fig2dev $*.fig $*.pict2e

all: $(PICTS)

