PICTS = 2odfII.pict2e IIRblockI.pict2e IIRblockII.pict2e IIRsfg.pict2e add.pict2e altsfg.pict2e assocprop.pict2e blockd.pict2e blockdf1.pict2e cascFIR.pict2e cascade.pict2e cascfosa.pict2e cascfosb.pict2e cascfosc.pict2e commprop.pict2e dIIsos.pict2e delay.pict2e directFIR.pict2e discsys.pict2e distrprop.pict2e eg1.pict2e eg2.pict2e egdfI.pict2e egdfII.pict2e egsfg.pict2e egsfg2.pict2e egsfg3.pict2e egsfg3trans.pict2e egsfg3trans2.pict2e feedback.pict2e ldiv.pict2e ldiv2.pict2e moveav.pict2e moverec.pict2e mult.pict2e noncomp.pict2e noncompmod.pict2e parrel.pict2e polezero.pict2e recrrepr.pict2e rscirc.pict2e rss.pict2e sfgI.pict2e sfgII.pict2e sigflow.pict2e sotsfg.pict2e sz.pict2e transdirectFIR.pict2e zlambda.pict2e

%.pict2e: %.fig
	fig2dev $*.fig $*.pict2e

all: $(PICTS)

