PICTS = capacitor.pict2e capacitor2.pict2e egnet.pict2e egnetxf.pict2e \
		imped.pict2e inductor.pict2e inductor2.pict2e parcapac.pict2e \
		parcapac2.pict2e parinduct.pict2e parinduct2.pict2e resistor.pict2e \
		rlc.pict2e sln.pict2e sln2.pict2e

%.pict2e: %.fig
	fig2dev $*.fig $*.pict2e

all: $(PICTS)

