PICTS = BFa.pict2e BFb.pict2e BFc.pict2e base.pict2e bfly.pict2e chirp.pict2e circa.pict2e circb.pict2e circc.pict2e circd.pict2e cvs.pict2e dft1.pict2e dft2.pict2e dft3.pict2e dft4.pict2e dft5.pict2e dft6.pict2e dft7.pict2e dft8.pict2e dif1.pict2e dif2.pict2e dif3.pict2e dif4.pict2e dif5.pict2e dif6.pict2e sfg1.pict2e sfg2.pict2e tpair.pict2e

%.pict2e: %.fig
	fig2dev $*.fig $*.pict2e

all: $(PICTS)

